export {default as Home} from './Home';
export {default as Testimonials} from './Testimonials';
export {default as Login} from './Login';
export {default as Register} from './Register';
export {default as CreateProfile} from './CreateProfile';
export {default as Profile} from './Profile';
export {default as Calendar} from './Calendar';
export {default as Workouts} from './Workouts';
export {default as Photos} from './Photos';
export {default as FriendPosts} from './FriendPosts';
export {default as Logo} from './Logo';
export {default as CreatePost} from './CreatePost';
export {default as Posts} from './Posts';
export {default as Footer} from './Footer';
export {default as SearchResults} from './SearchResults'